name: google_cloud_translation
description: Flutter API for google cloud translation.
version: 0.0.1+1
homepage: https://github.com/awaik/google_cloud_translation

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
